### ISSUE TITLE
Question about Boosted PPO 

### ISSUE THREAD

**Issue by GHysmu** [Kyziridis/BipedalWalker-v2#3]
I don't find the Boosted PPO in the file. There are two simple PPO, I want to know which is the Boosted PPO? Thank you!

**Comment by Kyziridis** [comment]
Hi,

There are two ppo implementations one is with keras and the other with tf.
The one implemented with tf is a more advanced ppo algorithm coming from
openAI. I just named it boosted because it uses a smarter way of the loss
function of Critic. Using some clipping functions. The other one in keras
is more simple and it does not have promising results.

I hope that it helps. Just use the tensor flow version PPO and play around
with different values for the parameters.

Good luck,
If you enjoy the repo, please give a star,
If you need any more help let me know.

All the best

**Comment by Kyziridis** [comment]
> I don't find the Boosted PPO in the file. There are two simple PPO, I want to know which is the Boosted PPO? Thank you!

The file you seek is under the folder PPO/external_PPO/rl-bipedal.py

**Comment by GHysmu** [comment]
Thank you for your reply! I am trying to use the DRL algorithm in the BipedalWalker-v3, your code helps me a lot!
